language: node_js
script: sbt coveralls && npm test
node_js:
- 0.1
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget http://dl.bintray.com/sbt/debian/sbt-0.13.5.deb
- sudo dpkg -i sbt-0.13.5.deb
after_failure:
- cat logs/application.log
- wget -O - https://unitcover.herokuapp.com/scripts/upload.sh | bash pussinboots unitcover ./target/test-reports/
- scripts/bliss scripts/upload_junitreport.sh
before_deploy:
- wget -O - https://unitcover.herokuapp.com/scripts/upload.sh | bash pussinboots unitcover ./target/test-reports/
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
  - $HOME/.ivy2
deploy:
  provider: heroku
  app: unitcover
  strategy: git
  api_key:
    secure: D1OyD4rxP9TAvmbYtHHFdRJHuNdoaiuEHmex1QRylqYO3nggelDSBbogajAZPlbwHANkCOnHIPEEgP3zSthjKSZd2xWik7bYUSxYn3RmdQydIxq4NKoINoNeYoRSaRpXjcDxL9gr05B4C/qAd1s9UoAE/d01S+Dgdu12tGkH9Xg=
