language: node_js
script: sbt test && npm test

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
  - sudo apt-get update
  - sudo apt-get install sbt
  - mkdir -p  $HOME/.sbt/launchers/0.13.17/
  - curl -L -o $HOME/.sbt/launchers/0.13.17/sbt-launch.jar https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.17/sbt-launch.jar

after_failure:
  - cat logs/application.log
  - scripts/bliss wget -O - https://unitcover.herokuapp.com/scripts/upload.sh |
    bash /dev/stdin pussinboots unitcover ./target/test-reports/
    "test-results.xml test-results-live.xml"

before_deploy:
  - scripts/bliss wget -O - https://unitcover.herokuapp.com/scripts/upload.sh |
    bash /dev/stdin pussinboots unitcover
    ./target/test-reports/  "test-results.xml test-results-live.xml"
  - ls -lha ./
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - ls -lha ./

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

deploy:
  provider: heroku
  app: unitcover
  skip_cleanup: true
  strategy: git
  api_key:
    secure: D1OyD4rxP9TAvmbYtHHFdRJHuNdoaiuEHmex1QRylqYO3nggelDSBbogajAZPlbwHANkCOnHIPEEgP3zSthjKSZd2xWik7bYUSxYn3RmdQydIxq4NKoINoNeYoRSaRpXjcDxL9gr05B4C/qAd1s9UoAE/d01S+Dgdu12tGkH9Xg=

after_deploy:
  - scripts/karma.sh e2elive
